Repository NVIDIA/recsys-examples, pull requests merged in 2025-04, with the labels that each got.

#2 add dockerfile; fix dynamicemb import error
  CONTRIBUTING.md
  README.md
  corelib/dynamicemb/dynamicemb/__init__.py
  corelib/dynamicemb/dynamicemb/batched_dynamicemb_compute_kernel.py
  corelib/dynamicemb/dynamicemb/batched_dynamicemb_function.py
  corelib/dynamicemb/dynamicemb/batched_dynamicemb_tables.py
  corelib/dynamicemb/dynamicemb/dump_load.py
  corelib/dynamicemb/dynamicemb/incremental_dump.py
  corelib/dynamicemb/dynamicemb/input_dist.py
  corelib/dynamicemb/dynamicemb/optimizer.py
  corelib/dynamicemb/dynamicemb/planner/__init__.py
  corelib/dynamicemb/dynamicemb/shard/__init__.py
  corelib/dynamicemb/dynamicemb/unique_op.py
  corelib/dynamicemb/test/test_optimizer.py
  corelib/dynamicemb/test/test_unique_op.py
  corelib/dynamicemb/test/unit_tests/incremental_dump/test_batched_dynamicemb_tables.py
  corelib/dynamicemb/test/unit_tests/test_sequence_embedding_bw.py
  docker/Dockerfile
  examples/hstu/modules/embedding.py
Labels: feature

#28 Fix license of source files in dynamicemb
  corelib/dynamicemb/src/check.h
  corelib/dynamicemb/src/dynamic_emb_op.cu
  corelib/dynamicemb/src/dynamic_variable_base.cu
  corelib/dynamicemb/src/dynamic_variable_base.h
  corelib/dynamicemb/src/hkv_variable.cuh
  corelib/dynamicemb/src/hkv_variable.h
  corelib/dynamicemb/src/index_calculation.cu
  corelib/dynamicemb/src/index_calculation.h
  corelib/dynamicemb/src/lookup_backward.cu
  corelib/dynamicemb/src/lookup_backward.h
  corelib/dynamicemb/src/lookup_forward.cu
  corelib/dynamicemb/src/lookup_forward.h
  corelib/dynamicemb/src/lookup_kernel.cuh
  corelib/dynamicemb/src/module_bind.cu
  corelib/dynamicemb/src/optimizer.cu
  corelib/dynamicemb/src/optimizer.h
  corelib/dynamicemb/src/optimizer_kernel.cuh
  corelib/dynamicemb/src/sparse_block_bucketize_features.cu
  corelib/dynamicemb/src/sparse_block_bucketize_features_utils.h
  corelib/dynamicemb/src/torch_utils.cu
  corelib/dynamicemb/src/torch_utils.h
  corelib/dynamicemb/src/unique_op.cu
  corelib/dynamicemb/src/unique_op.h
  corelib/dynamicemb/src/unique_variable.cu
  corelib/dynamicemb/src/unique_variable.h
  corelib/dynamicemb/src/utils.cpp
  corelib/dynamicemb/src/utils.h
Labels: documentation, dynamicemb

#25 [Test] Fix wrong import path
  examples/hstu/test/test_ranking_gr.py
Labels: bugfix

#26 [Test ]Restore test_twin_module.sh tests and remove cases for Adam and AdamW.
  corelib/dynamicemb/test/unit_test.sh
  corelib/dynamicemb/test/unit_tests/test_twin_module.py
Labels: bugfix, dynamicemb

#29 fix test_embedding.py
  examples/hstu/test/test_embedding.py
Labels: bugfix
